import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { spawn, execFileSync } from 'node:child_process';
import { mkdirSync, closeSync, openSync } from 'node:fs';
import path from 'node:path';

let server;
let serverEnv;
test.beforeAll(async () => {
    test.setTimeout(60_000);
    const directory = path.resolve('storage/framework/testing');
    mkdirSync(directory, { recursive: true });
    const database = path.join(directory, 'purchase-browser.sqlite');
    closeSync(openSync(database, 'a'));
    const env = { ...process.env, APP_ENV: 'testing', DB_CONNECTION: 'sqlite', DB_DATABASE: database, DB_URL: '', CACHE_STORE: 'array', SESSION_DRIVER: 'file', DEBUGBAR_ENABLED: 'false', TELESCOPE_ENABLED: 'false', NIGHTWATCH_ENABLED: 'false', APP_CONFIG_CACHE: path.join(directory, 'unused-purchase-config.php') };
    serverEnv = env;
    execFileSync('php', ['tests/Browser/support/purchase-fixture.php'], { env, stdio: 'pipe' });
    server = spawn('php', ['-S', '127.0.0.1:8027', path.resolve('vendor/laravel/framework/src/Illuminate/Foundation/resources/server.php')], { cwd: path.resolve('public'), env, stdio: 'pipe', windowsHide: true });
    let serverOutput = '';
    server.stdout.on('data', data => { serverOutput += data; });
    server.stderr.on('data', data => { serverOutput += data; });
    for (let attempt = 0; attempt < 60; attempt++) {
        try { if ((await fetch('http://127.0.0.1:8027/login')).ok) return; } catch {}
        await new Promise(resolve => setTimeout(resolve, 500));
    }
    throw new Error(`Isolated purchase server did not start: ${serverOutput}`);
});
test.afterAll(() => { server?.kill(); });

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
    test(`meal inventory cook consume and revert at ${viewport.width}px`, async ({ page }) => {
        test.setTimeout(120_000);
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.setViewportSize(viewport);
        await page.goto('/login');
        await page.getByLabel('Correo electrónico').fill('purchase-browser@example.test');
        await page.getByLabel('Contraseña', { exact: true }).fill('browser-test-password');
        await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
        await page.waitForURL(url => !url.pathname.includes('/login'));
        await page.goto('/meals/preparations');
        await page.getByRole('button', { name: 'Cocinar preparación', exact: true }).click();
        const cook = page.getByRole('dialog', { name: 'Cocinar preparación' });
        await cook.getByLabel('Receta', { exact: true }).selectOption({ label: 'Sopa de inventario' });
        await cook.getByLabel('Porciones producidas').fill('6');
        await cook.getByRole('button', { name: 'Guardar', exact: true }).click();
        await expect(cook).not.toBeVisible();
        await expect(page.locator('#meal-preparations')).toContainText('Producidas: 6');
        await page.goto('/meals/weekly');
        const breakfast = page.locator('tr').filter({ has: page.locator('td.meal-week-grid__type', { hasText: 'Desayuno' }) }).locator('.meal-slot').first();
        await breakfast.focus();
        await page.keyboard.press('Enter');
        const editor = page.getByRole('dialog');
        await editor.locator('#meal-preparation').selectOption({ label: 'Sopa de inventario · 6 porciones sin reservar' });
        await editor.getByRole('button', { name: 'Añadir preparación', exact: true }).click();
        await editor.locator('#meal-portions-0').fill('2');
        await editor.getByRole('button', { name: 'Guardar', exact: true }).click();
        await expect(editor).not.toBeVisible();
        await breakfast.click();
        await editor.getByRole('button', { name: 'Marcar consumida', exact: true }).click();
        await expect(editor).toContainText('Comida consumida');
        await expect(editor.locator('#meal-portions-0')).toBeDisabled();
        await editor.getByRole('button', { name: 'Revertir consumo', exact: true }).click();
        await expect(editor.getByRole('button', { name: 'Marcar consumida', exact: true })).toBeVisible();
        page.once('dialog', dialog => dialog.accept());
        await editor.getByRole('button', { name: 'Eliminar', exact: true }).click();
        await expect(editor).not.toBeVisible();
        await page.goto('/meals/preparations');
        await expect(page.locator('#meal-preparations')).toContainText('Reservadas: 0');
        page.once('dialog', dialog => dialog.accept());
        await page.getByRole('button', { name: 'Cancelar preparación', exact: true }).click();
        await expect(page.locator('#meal-preparations')).not.toContainText('Sopa de inventario');
        await page.goto('/meals/weekly');
        await breakfast.click();
        await editor.locator('button[wire\\:click="addCustomItem"]').click();
        await editor.locator('#meal-custom-name-0').fill('Leche con torta');
        for (const [index, product, quantity, unit] of [[0, 'Leche de consumo (ml)', '250', 'ml'], [1, 'Torta de consumo (g)', '50', 'g']]) {
            await editor.getByRole('button', { name: 'Enlazar ingrediente', exact: true }).click();
            await editor.locator(`#meal-product-0-${index}`).selectOption({ label: product });
            await editor.locator(`#meal-quantity-0-${index}`).fill(quantity);
            await editor.locator(`#meal-unit-0-${index}`).fill(unit);
        }
        const violations = (await new AxeBuilder({ page }).include('[role="dialog"]').withRules(['button-name', 'label', 'select-name', 'aria-valid-attr-value']).analyze()).violations;
        expect(violations).toEqual([]);
        expect(await editor.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
        await editor.getByRole('button', { name: 'Marcar consumida', exact: true }).click();
        await expect(editor).toContainText('Comida consumida');
        await editor.getByRole('button', { name: 'Revertir consumo', exact: true }).click();
        await editor.getByRole('button', { name: 'Comí por fuera', exact: true }).click();
        await expect(editor).toContainText('Comida por fuera');
        await editor.getByRole('button', { name: 'Revertir consumo', exact: true }).click();
        page.once('dialog', dialog => dialog.accept());
        await editor.getByRole('button', { name: 'Eliminar', exact: true }).click();
        await expect(editor).not.toBeVisible();
        await page.goto('/meals/suggestions');
        await expect(page.getByText('Productos próximos a vencer', { exact: true })).toBeVisible();
        expect(errors).toEqual([]);
    });
    test(`meal planning loads dinner editor at ${viewport.width}px`, async ({ page }) => {
        test.setTimeout(60_000);
        await page.setViewportSize(viewport);
        await page.goto('/login');
        await page.getByLabel('Correo electrónico').fill('purchase-browser@example.test');
        await page.getByLabel('Contraseña', { exact: true }).fill('browser-test-password');
        await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
        await page.waitForURL(url => !url.pathname.includes('/login'));
        await page.goto('/meals/weekly');
        await page.locator('.meal-slot').filter({ hasText: 'Sopa de prueba' }).click();
        const dialog = page.getByRole('dialog');
        await expect(dialog).toBeVisible();
        await expect(dialog).toContainText('Editar cena');
        await expect(dialog.locator('#meal-custom-name-0')).toHaveValue('Sopa de prueba');
        await expect(dialog.locator('#meal-notes')).toHaveValue('Cena de prueba');
        await expect(dialog.locator('#meal-calories')).toHaveValue('420');
        await dialog.locator('#meal-notes').fill('Cena editada');
        await dialog.getByRole('button', { name: 'Actualizar', exact: true }).click();
        await expect(dialog).not.toBeVisible();
        await page.locator('.meal-slot').filter({ hasText: 'Sopa de prueba' }).click();
        await expect(dialog.locator('#meal-notes')).toHaveValue('Cena editada');
        await dialog.locator('#meal-notes').fill('Cena de prueba');
        await dialog.getByRole('button', { name: 'Actualizar', exact: true }).click();
        await expect(dialog).not.toBeVisible();
        await page.locator('.meal-slot').filter({ hasText: 'Sopa de prueba' }).click();
        await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click();
        await expect(dialog).not.toBeVisible();
        await page.locator('tr').filter({ has: page.locator('td.meal-week-grid__type', { hasText: 'Desayuno' }) }).locator('.meal-slot').first().click();
        await expect(dialog).toContainText('Planear desayuno');
        await expect(dialog.locator('#meal-notes')).toHaveValue('');
        await dialog.locator('button[wire\\:click="addCustomItem"]').click();
        await expect(dialog.locator('#meal-custom-name-0')).toBeVisible();
        expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
        await page.keyboard.press('Escape');
        await expect(dialog).not.toBeVisible();
    });
    test(`management refresh without navigation at ${viewport.width}px`, async ({ page }) => {
        await page.setViewportSize(viewport);
        await page.goto('/login');
        await page.getByLabel('Correo electrónico').fill('purchase-browser@example.test');
        await page.getByLabel('Contraseña', { exact: true }).fill('browser-test-password');
        await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
        await page.waitForURL(url => !url.pathname.includes('/login'));
        await page.goto('/meals/ingredients?q=Pan');
        const card = page.locator('#meal-ingredients');
        const trigger = card.getByRole('button', { name: 'Más acciones de catálogo de ingredientes' });
        await expect(trigger).toHaveCount(1);
        await page.evaluate(() => { window.refreshDocumentMarker = 'same-document'; });
        const updatedStock = viewport.width === 1440 ? '123' : '456';
        execFileSync('php', ['tests/Browser/support/purchase-fixture.php', '--update-stock', updatedStock], { env: serverEnv, stdio: 'pipe' });
        await trigger.focus();
        await page.keyboard.press('Enter');
        const refresh = card.getByRole('menuitem', { name: 'Actualizar tabla' });
        await expect(refresh).toBeVisible();
        let releaseRefresh;
        const heldRequest = new Promise(resolve => { releaseRefresh = resolve; });
        await page.route(/livewire.*\/update/, async route => { await heldRequest; await route.continue(); });
        const refreshRequest = page.waitForRequest(request => request.method() === 'POST' && /livewire.*\/update/.test(request.url()));
        await refresh.focus();
        await page.keyboard.press('Enter');
        await refreshRequest;
        await expect(refresh).toBeDisabled();
        releaseRefresh();
        await expect(card).toContainText(updatedStock);
        await expect(refresh).not.toBeVisible();
        expect(await page.evaluate(() => window.refreshDocumentMarker)).toBe('same-document');
        expect(new URL(page.url()).searchParams.get('q')).toBe('Pan');
        await trigger.click();
        await page.keyboard.press('Escape');
        await expect(trigger).toBeFocused();
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    });
    test(`purchase create, detail and edit at ${viewport.width}px`, async ({ page }) => {
        await page.setViewportSize(viewport);
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.goto('/login');
        await page.getByLabel('Correo electrónico').fill('purchase-browser@example.test');
        await page.getByLabel('Contraseña', { exact: true }).fill('browser-test-password');
        await page.getByRole('button', { name: 'Iniciar Sesión' }).click();
        await page.waitForURL(url => !url.pathname.includes('/login'));
        await page.goto('/meals/shopping');
        if (viewport.width < 768) {
            await page.locator('.md-fab-split__compact').click();
        } else {
            await page.getByRole('button', { name: 'Más acciones de creación', exact: true }).click();
        }
        await page.getByRole('menuitem', { name: 'Registrar compra', exact: true }).click();
        const dialog = page.getByRole('dialog', { name: 'Registrar compra' });
        await expect(dialog).toBeVisible();
        await dialog.getByRole('combobox', { name: 'Tienda', exact: true }).selectOption({ label: 'Tienda de prueba' });
        if (viewport.width < 768) await dialog.getByRole('button', { name: 'Mostrar u ocultar secciones' }).click();
        await dialog.getByRole('button', { name: 'Productos', exact: true }).click();
        const line = dialog.locator('fieldset').first();
        await line.getByRole('combobox', { name: 'Producto', exact: true }).selectOption({ label: 'Pan de prueba' });
        await line.getByLabel('Presentación').selectOption({ index: 1 });
        await line.getByRole('spinbutton', { name: 'Paquetes', exact: true }).fill('2');
        await line.getByLabel('Precio final por paquete').fill('10');
        await dialog.getByRole('button', { name: 'Añadir línea' }).click();
        const second = dialog.locator('fieldset').nth(1);
        await second.getByRole('combobox', { name: 'Producto', exact: true }).selectOption({ label: 'Leche de prueba' });
        await second.getByRole('spinbutton', { name: 'Paquetes', exact: true }).fill('1');
        await expect(dialog.getByRole('status')).toContainText('incompleta');
        const violations = (await new AxeBuilder({ page }).include('[role="dialog"]').withRules(['button-name', 'label', 'select-name', 'aria-valid-attr-value']).analyze()).violations;
        expect(violations).toEqual([]);
        expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
        await page.screenshot({ path: `storage/framework/testing/purchase-previews/editor-${viewport.width}.png` });
        await dialog.getByRole('button', { name: 'Guardar', exact: true }).click();
        await expect(dialog).not.toBeVisible();
        await page.goto('/meals/purchases');
        await expect(page.getByText('2 líneas', { exact: false }).first()).toBeVisible();
        if (viewport.width < 768) {
            await page.locator('.md-row-actions__more').first().click();
            await page.getByRole('menuitem', { name: 'Ver detalle', exact: true }).first().click();
        } else {
            await page.getByRole('button', { name: 'Ver detalle', exact: true }).first().click();
        }
        const detail = page.getByRole('dialog', { name: 'Detalle de compra' });
        await expect(detail).toContainText('Pan de prueba');
        await page.keyboard.press('Escape');
        await expect(detail).not.toBeVisible();
        await page.locator('.md-row-actions__more').first().click();
        await page.getByRole('menuitem', { name: 'Editar', exact: true }).first().click();
        const editor = page.getByRole('dialog', { name: 'Editar compra' });
        await expect(editor).toBeVisible();
        if (viewport.width < 768) await editor.getByRole('button', { name: 'Mostrar u ocultar secciones' }).click();
        await editor.getByRole('button', { name: 'Detalles', exact: true }).click();
        await editor.getByLabel('Notas').fill(`Editada desde ${viewport.width}px`);
        await editor.getByRole('button', { name: 'Guardar', exact: true }).click();
        await expect(editor).not.toBeVisible();
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
        expect(errors).toEqual([]);
    });
}

