@if($showEnergyForm)
    <div class="md-dialog-backdrop"><div class="md-dialog vehicle-energy-dialog">
        <div class="d-flex justify-content-between align-items-center mb-3"><h2 class="md-title-large mb-0">{{ $energyUi['form'] }}</h2><button wire:click="$set('showEnergyForm', false)" class="md-btn-icon"><i class="bi bi-x-lg"></i></button></div>
        <div class="row g-3">
            <div class="col-md-4"><label class="form-label">Fecha</label><input wire:model="energyDate" type="date" class="form-control">@error('energyDate')<small class="text-danger">{{ $message }}</small>@enderror</div>
            <div class="col-md-4"><label class="form-label">Tipo</label><select wire:model.live="energySource" class="form-select">@foreach($energySources as $source)<option value="{{ $source }}">{{ $source === 'electrico' ? 'Electricidad' : ucfirst($source) }}</option>@endforeach</select></div>
            <div class="col-md-4"><label class="form-label">Cantidad {{ $energyCalculatedField === 'quantity' ? '(calculada)' : '' }}</label><div class="input-group"><input wire:model.live.debounce.300ms="energyQuantity" type="number" step=".01" min="0" class="form-control {{ $energyCalculatedField === 'quantity' ? 'bg-light' : '' }}"><span class="input-group-text">{{ $energyUnit }}</span></div>@error('energyQuantity')<small class="text-danger">{{ $message }}</small>@enderror</div>
            <div class="col-md-6"><label class="form-label">Precio por {{ $energyUnit }} {{ $energyCalculatedField === 'unit_price' ? '(calculado)' : '' }}</label><input wire:model.live.debounce.300ms="energyUnitPrice" type="number" step=".01" min="0" class="form-control {{ $energyCalculatedField === 'unit_price' ? 'bg-light' : '' }}">@error('energyUnitPrice')<small class="text-danger">{{ $message }}</small>@enderror</div>
            <div class="col-md-6"><label class="form-label">Costo total {{ $energyCalculatedField === 'cost' ? '(calculado)' : '' }}</label><input wire:model.live.debounce.300ms="energyCost" type="number" step=".01" min="0" class="form-control {{ $energyCalculatedField === 'cost' ? 'bg-light' : '' }}">@error('energyCost')<small class="text-danger">{{ $message }}</small>@enderror</div>
            <div class="col-md-6"><label class="form-label">Lectura {{ $vehicle->usage_unit }}</label><input wire:model="energyUsageReading" type="number" step=".01" min="0" class="form-control">@error('energyUsageReading')<small class="text-danger">{{ $message }}</small>@enderror</div>
            <div class="col-12"><label class="d-flex align-items-center gap-2 md-body-medium"><input wire:model="energyIsFull" type="checkbox"> {{ $energySource === 'electrico' ? 'Carga completa' : 'Tanque lleno' }}</label><div class="md-body-small text-muted">Dos llenados completos con lectura permiten calcular el rendimiento.</div></div>
            <div class="col-md-6"><label class="form-label">Proveedor</label><input wire:model="energyProvider" class="form-control" placeholder="Estación o punto de carga"></div><div class="col-md-6"><label class="form-label">Nota</label><input wire:model="energyNotes" class="form-control"></div>
        </div>
        <div class="md-dialog-actions mt-4"><button wire:click="$set('showEnergyForm', false)" class="md-btn-text">Cancelar</button><button wire:click="saveEnergyLog" class="md-btn-filled">{{ $editingEnergyLogId ? 'Guardar cambios' : 'Guardar registro' }}</button></div>
    </div></div>
@endif
