<x-module-shell module="vehicles" title="Catálogo de mantenimientos" subtitle="Plantillas base y personales para tu garaje." icon="bi-tools">
    <x-slot:actions><x-module-actions mobile-style="inline" :primary="['label' => 'Nueva plantilla', 'icon' => 'bi-plus-lg', 'action' => 'openTemplateForm']" :secondary="[['label' => 'Volver al garaje', 'icon' => 'bi-arrow-left', 'href' => route('vehicles')]]" /></x-slot:actions>

    @if($catalogMessage)<div class="md-card-outlined mb-3 py-2 px-3 md-body-medium vehicle-catalog-message">{{ $catalogMessage }}</div>@endif
    <section class="md-card-outlined vehicle-catalog-filters">
        <div class="vehicle-section-heading"><div><h2>Filtrar catálogo</h2><p>{{ $catalogTemplates->total() }} resultados</p></div><button wire:click="clearCatalogFilters" class="md-btn-text">Limpiar</button></div>
        <div class="vehicle-filter-grid"><div class="vehicle-filter-search"><label class="visually-hidden" for="catalog-search">Buscar</label><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input id="catalog-search" wire:model.live.debounce.300ms="catalogSearch" class="form-control" placeholder="Buscar nombre o descripción"></div></div><select wire:model.live="catalogCategory" class="form-select"><option value="">Categorías</option>@foreach($catalogCategories as $category)<option value="{{ $category }}">{{ $category }}</option>@endforeach</select><select wire:model.live="catalogSource" class="form-select"><option value="">Base y personal</option><option value="base">Solo base</option><option value="personal">Solo personal</option></select><select wire:model.live="catalogVehicleType" class="form-select"><option value="">Todos los vehículos</option><option value="automovil">Automóvil</option><option value="motocicleta">Motocicleta</option><option value="bicicleta">Bicicleta</option><option value="patineta">Patineta</option><option value="otro">Otro</option></select><select wire:model.live="catalogPowerSource" class="form-select"><option value="">Toda propulsión</option><option value="gasolina">Gasolina</option><option value="diesel">Diésel</option><option value="electrico">Eléctrica</option><option value="hibrido">Híbrida</option><option value="humana">Humana</option><option value="ninguna">Ninguna</option></select><select wire:model.live="catalogTransmissionType" class="form-select"><option value="">Todas las transmisiones</option><option value="manual">Manual</option><option value="automatica">Automática</option><option value="cvt">CVT</option><option value="automatizada">Automatizada</option><option value="no_aplica">No aplica</option></select></div>
    </section>

    <div class="vehicle-catalog-grid">
        @forelse($catalogTemplates as $template)<article class="md-card-outlined"><header><div><span>{{ $template->category }}</span><h2>{{ $template->name }}</h2></div><small>{{ $template->user_id ? 'Personal' : 'Base' }}</small></header><p>{{ $template->description ?: 'Sin descripción.' }}</p><div class="vehicle-catalog-card__footer"><span>{{ $template->default_interval_days ? 'Cada '.$template->default_interval_days.' días' : 'Sin periodo' }}{{ $template->default_interval_days && $template->default_interval_usage ? ' · ' : '' }}{{ $template->default_interval_usage ? number_format($template->default_interval_usage, 0, ',', '.').' de uso' : '' }}</span>@if($template->user_id)<div><button wire:click="openTemplateForm('{{ $template->id }}')" class="md-btn-icon"><i class="bi bi-pencil"></i></button><button wire:click="deleteTemplate('{{ $template->id }}')" wire:confirm="¿Eliminar esta plantilla?" class="md-btn-icon text-danger"><i class="bi bi-trash"></i></button></div>@endif</div></article>@empty<div class="md-empty-state md-card-outlined"><div class="md-empty-state__icon"><i class="bi bi-tools"></i></div><h2>No hay plantillas disponibles</h2></div>@endforelse
    </div>
    <div class="vehicle-pagination">{{ $catalogTemplates->links() }}</div>

    @include('livewire.vehicle.partials.template-form')
</x-module-shell>
