import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import AxeBuilder from '@axe-core/playwright';
const runId = Date.now();
const eventTitle = `Performance synthetic symptom ${runId}`;
const taskTitle = `Performance synthetic task ${runId}`;
const browser = await chromium.launch();
const context = await browser.newContext({viewport:{width:1440,height:900},serviceWorkers:'block'});
const page = await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
let posts=0;
page.on('request',r=>{if(r.method()==='POST')posts++;});
try {
    await page.goto('http://127.0.0.1:8031/login');
    await page.getByLabel('Correo electrónico').fill('small@performance.test');
    await page.getByLabel('Contraseña',{exact:true}).fill('password');
    await page.getByRole('button',{name:/Iniciar Sesión/}).click();
    await page.waitForURL('http://127.0.0.1:8031/');
    await page.goto('http://127.0.0.1:8031/health');
    const initial=posts;
    await page.getByRole('button',{name:'Registrar evento',exact:true}).click();
    const health=page.getByRole('dialog').filter({visible:true});
    await expect(health).toBeVisible();
    await expect.poll(()=>posts).toBe(initial);
    await health.locator('select[name=type]').selectOption('symptom');
    await expect(health.locator('.md-multi-select__trigger')).toBeVisible();
    await health.locator('.md-multi-select__trigger').click();
    await health.getByLabel('Cabeza',{exact:true}).check();
    await health.locator('.md-multi-select__trigger').click();
    await health.locator('input[name=title]').fill(eventTitle);
    await health.locator('select[name=initialIntensity]').selectOption('3');
    await health.getByRole('button',{name:'Resumen',exact:true}).click();
    await expect(health.locator('dd').filter({hasText:eventTitle})).toBeVisible();
    await expect(health.locator('dd').filter({hasText:'Cabeza'})).toBeVisible();
    if(posts!==initial)throw new Error('Draft generated network requests');
    await health.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(health).toBeHidden();
    await expect(page.getByRole('button',{name:new RegExp(eventTitle)})).toBeVisible();
    await page.getByRole('button',{name:new RegExp(eventTitle)}).click();
    await page.locator('.health-event').filter({hasText:eventTitle}).getByRole('button',{name:/Más/}).last().click();
    await page.getByRole('menuitem',{name:'Editar evento',exact:true}).click();
    await expect(health.locator('input[name=title]')).toHaveValue(eventTitle);
    await health.getByRole('button',{name:'Cerrar',exact:true}).click();
    await expect(health).toBeHidden();
    for(const width of [390,768,1440]) {
        await page.setViewportSize({width,height:900});
        const opener=page.getByRole('button',{name:'Registrar evento',exact:true});
        await opener.click();
        await expect(health).toBeVisible();
        await health.locator('input[name=title]').focus();
        await page.keyboard.press('Tab');
        expect(await health.evaluate(el=>el.contains(document.activeElement))).toBe(true);
        const result=await new AxeBuilder({page}).include('.md-form-dialog-layer:not([style*="display: none"])').withRules(['button-name','label','select-name','aria-valid-attr-value','duplicate-id-aria']).analyze();
        expect(result.violations).toEqual([]);
        await health.locator('select[name=type]').selectOption('symptom');
        await health.locator('.md-multi-select__trigger').click();
        await page.keyboard.press('Escape');
        await expect(health).toBeVisible();
        await page.keyboard.press('Escape');
        await expect(health).toBeHidden();
        await expect(opener).toBeFocused();
    }
    await page.getByRole('button',{name:'Registrar evento',exact:true}).click();
    await expect(health.locator('input[name=title]')).toHaveValue('');
    await health.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(health.locator('[role=alert]').filter({visible:true}).first()).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(health).toBeHidden();
    await page.getByRole('button',{name:'Registrar evento',exact:true}).click();
    await expect(health.locator('[aria-invalid="true"]')).toHaveCount(0);
    await expect(health.locator('[role=alert]').filter({visible:true})).toHaveCount(0);
    await health.getByRole('button',{name:'Cerrar',exact:true}).click();
    const beforeFilters=posts;
    await page.locator('.health-filter-button').click();
    await page.locator('#health-filters select[name=status]').selectOption('active');
    expect(posts).toBe(beforeFilters);
    await page.locator('#health-filters').getByRole('button',{name:'Aplicar',exact:true}).click();
    await page.waitForURL(url=>url.searchParams.get('status')==='active');
    await page.goBack();
    await page.waitForFunction(()=>window.Livewire.find(document.querySelector('[wire\\:name="health.health-index"]').getAttribute('wire:id')).status==='all');
    await page.goForward();
    await page.waitForFunction(()=>window.Livewire.find(document.querySelector('[wire\\:name="health.health-index"]').getAttribute('wire:id')).status==='active');
    await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click();
    await page.waitForURL(url=>url.searchParams.get('status')==='all');
    await page.getByRole('link',{name:'Tareas',exact:true}).first().click();
    await page.getByRole('button',{name:'Nueva tarea',exact:true}).click();
    const task=page.getByRole('dialog').filter({visible:true});
    await expect(task).toBeVisible();
    const beforeRecurrence=posts;
    await task.getByRole('button',{name:/Programación/}).click();
    await task.getByLabel('Tarea recurrente',{exact:true}).check();
    await expect(task.locator('#task-editor-recurrence-days')).toBeVisible();
    await task.getByLabel('Tarea recurrente',{exact:true}).uncheck();
    expect(posts).toBe(beforeRecurrence);
    await task.getByRole('button',{name:/Lo básico/}).click();
    await task.locator('input[id$="-title"]').fill(taskTitle);
    await task.getByRole('button',{name:'Guardar',exact:true}).click();
    await expect(task).toBeHidden();
    await expect(page.getByRole('button',{name:new RegExp(taskTitle)}).first()).toBeVisible();
    await page.getByRole('button',{name:new RegExp('Abrir tarea: '+taskTitle)}).click();
    await expect(task.locator('input[id$="-title"]')).toHaveValue(taskTitle);
    const taskId=await page.evaluate(()=>window.Livewire.find(document.querySelector('[wire\\:name="task.task-editor"]').getAttribute('wire:id')).editingId);
    await task.getByRole('button',{name:'Cerrar',exact:true}).click();
    await page.goto(`http://127.0.0.1:8031/tasks/list?edit=${taskId}&status=pending`);
    await expect(task.locator('input[id$="-title"]')).toHaveValue(taskTitle);
    const beforeClose=posts;
    await task.getByRole('button',{name:'Cerrar',exact:true}).click();
    await expect(task).toBeHidden();
    await expect.poll(()=>new URL(page.url()).searchParams.has('edit')).toBe(false);
    expect(posts).toBe(beforeClose);
    for(const width of [390,768,1440]) {
        await page.setViewportSize({width,height:900});
        await page.getByRole('button',{name:'Nueva tarea',exact:true}).click();
        await expect(task).toBeVisible();
        await mkdir('storage/framework/testing/performance',{recursive:true});
        await page.screenshot({path:`storage/framework/testing/performance/task-${width}.png`});
        await task.getByRole('button',{name:'Cancelar',exact:true}).click();
        await expect(task).toBeHidden();
    }
    if(errors.length)throw new Error(JSON.stringify(errors));
    console.log('Editor regression checks passed: save, edit, fresh drafts, validation, Escape, responsive close, no draft requests.');
} catch(error) { console.error('Browser errors:', errors); await page.screenshot({path:'storage/framework/testing/performance/editor-failure.png'}); throw error; } finally { await browser.close(); }
